- title: "Overview"
  alt_title: "Applications"
  href: "guides/applications"
  
- title: "Fonts"
  href: "guides/applications/fonts"

- title: "Header"
  href: "guides/applications/header"

- title: "Navigation"
  href: "guides/applications/navigation"

- title: "Footer"
  href: "guides/applications/footer"

- title: "Buttons"
  href: "guides/applications/buttons"
  
- title: "Forms"
  href: "guides/applications/forms"
  
  - title: "Tables"
  href: "guides/applications/tables"

