- title: "Applications"
  alt_title: "Applications"
  href: "guides/applications"
  
- title: "Fonts"
  href: "guides/applications/fonts"

- title: "Header"
  href: "guides/applications/header"

- title: "Navigation"
  href: "guides/applications/navigation"

- title: "Footer"
  href: "guides/applications/footer"

- title: "Buttons"
  href: "guides/applications/buttons"
  
- title: "Forms"
  href: "guides/applications/forms"
  
- title: "Form Validation"
  href: "guides/applications/form-validation"
  
- title: "Tables"
  href: "guides/applications/tables"
  
- title: "Date Format"
  href: "guides/applications/date-format"